services:
  - type: web
    name: website-for-the-blind
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
